### ISSUE TITLE
Support for purpur entity fly ender dragon and riding mobs (suggestion) (maybe hard)

### ISSUE THREAD

**Issue by jokbon** [herobrine99dan/NESS-Reloaded#154]
Support for purpur (thats server software) entity fly ender dragon and riding other mobs.

    ```
mobs:
      pillager:
        bypass-mob-griefing: false
        ridable: false
        ridable-in-water: false
        attributes:
          max_health: 24.0
      phantom:
        allow-griefing: false
        flames-on-swoop: false
        ridable: false
        ridable-in-water: false
        ridable-max-y: 256.0
        attacked-by-crystal-range: 0.0
        attacked-by-crystal-damage: 1.0
        orbit-crystal-radius: 0.0
        burn-in-light: 0
        burn-in-daylight: true
        ignore-players-with-torch: false
        flames:
          damage: 1.0
          fire-time: 8
        spawn:
          min-sky-darkness: 5
          only-above-sea-level: true
          only-with-visible-sky: true
          local-difficulty-chance: 3.0
          min-time-since-slept: 72000
          delay:
            min: 1200
            max: 2400
          overhead:
            min: 20
            max: 35
            radius: 10
          per-attempt:
            min: 1
            max: -1
        attributes:
          max_health: 20.0
      bee:
        can-work-at-night: false
        can-work-in-rain: false
        ridable: false
        ridable-in-water: false
        ridable-max-y: 256.0
        breeding-delay-ticks: 6000
        attributes:
          max_health: 10.0
      cave_spider:
        ridable: false
        ridable-in-water: false
        attributes:
          max_health: 12.0
      blaze:
        takes-damage-from-water: true
        ridable: false
        ridable-in-water: false
        ridable-max-y: 256.0
        attributes:
          max_health: 20.0
      bat:
        ridable: false
        ridable-in-water: false
        ridable-max-y: 256.0
        attributes:
          max_health: 6.0
      cat:
        ridable: false
        ridable-in-water: false
        spawn-delay: 1200
        breeding-delay-ticks: 6000
        scan-range-for-other-cats:
          swamp-hut: 16
          village: 48
        attributes:
          max_health: 10.0
      chicken:
        ridable: false
        ridable-in-water: false
        retaliate: false
        breeding-delay-ticks: 6000
        attributes:
          max_health: 4.0
      cod:
        ridable: false
        attributes:
          max_health: 3.0
      drowned:
        ridable: false
        ridable-in-water: false
        jockey:
          only-babies: true
          chance: 0.05
          try-existing-chickens: true
        attributes:
          max_health: 20.0
          spawn_reinforcements: 0.1
      cow:
        ridable: false
        ridable-in-water: false
        feed-mushrooms-for-mooshroom: 0
        breeding-delay-ticks: 6000
        attributes:
          max_health: 10.0
      fox:
        bypass-mob-griefing: false
        ridable: false
        ridable-in-water: false
        tulips-change-type: false
        breeding-delay-ticks: 6000
        attributes:
          max_health: 10.0
      endermite:
        ridable: false
        ridable-in-water: false
        attributes:
          max_health: 8.0
      creeper:
        bypass-mob-griefing: false
        health-impacts-explosion: false
        explode-when-killed: false
        ridable: false
        ridable-in-water: false
        allow-griefing: true
        naturally-charged-chance: 0.0
        attributes:
          max_health: 20.0
      donkey:
        ridable-in-water: false
        breeding-delay-ticks: 6000
        attributes:
          max_health:
            min: 15.0
            max: 30.0
          jump_strength:
            min: 0.5
            max: 0.5
          movement_speed:
            min: 0.175
            max: 0.175
      dolphin:
        ridable: false
        disable-treasure-searching: false
        spit:
          cooldown: 20
          speed: 1.0
          damage: 2.0
        attributes:
          max_health: 10.0
      enderman:
        aggressive-towards-spawned-endermites: false
        ignore-players-wearing-dragon-head: false
        disable-player-stare-aggression: false
        bypass-mob-griefing: false
        takes-damage-from-water: true
        ridable: false
        ridable-in-water: false
        allow-griefing: true
        can-despawn-with-held-block: false
        attributes:
          max_health: 40.0
      evoker:
        bypass-mob-griefing: false
        ridable: false
        ridable-in-water: false
        attributes:
          max_health: 24.0
      ghast:
        allow-griefing: true
        ridable: false
        ridable-in-water: false
        ridable-max-y: 256.0
        attributes:
          max_health: 10.0
      horse:
        ridable-in-water: false
        breeding-delay-ticks: 6000
        attributes:
          max_health:
            min: 15.0
            max: 30.0
          jump_strength:
            min: 0.4
            max: 1.0
          movement_speed:
            min: 0.1125
            max: 0.3375
      iron_golem:
        poppy-calms-anger: false
        ridable: false
        ridable-in-water: false
        can-swim: false
        attributes:
          max_health: 100.0
      hoglin:
        ridable: false
        ridable-in-water: false
        breeding-delay-ticks: 6000
        attributes:
          max_health: 40.0
      illusioner:
        ridable: false
        ridable-in-water: false
        max-health: 32.0
        movement-speed: 0.5
        follow-range: 18.0
        attributes:
          max_health: 32.0
      magma_cube:
        ridable: false
        ridable-in-water: false
        attributes:
          max_health: size * size
      giant:
        ridable: false
        ridable-in-water: false
        step-height: 2.0
        jump-height: 1.0
        max-health: 100.0
        movement-speed: 0.5
        attack-damage: 50.0
        have-ai: false
        have-hostile-ai: false
        attributes:
          max_health: 100.0
      guardian:
        ridable: false
        attributes:
          max_health: 30.0
      husk:
        ridable: false
        ridable-in-water: false
        jockey:
          only-babies: true
          chance: 0.05
          try-existing-chickens: true
        attributes:
          max_health: 20.0
          spawn_reinforcements: 0.1
      llama:
        join-caravans: true
        ridable: false
        ridable-in-water: false
        breeding-delay-ticks: 6000
        attributes:
          max_health:
            min: 15.0
            max: 30.0
          jump_strength:
            min: 0.5
            max: 0.5
          movement_speed:
            min: 0.175
            max: 0.175
      piglin:
        bypass-mob-griefing: true
        portal-spawn-modifier: 2000
        ridable: false
        ridable-in-water: false
        attributes:
          max_health: 16.0
      mooshroom:
        ridable: false
        ridable-in-water: false
        breeding-delay-ticks: 6000
        attributes:
          max_health: 10.0
      parrot:
        can-breed: false
        ridable: false
        ridable-in-water: false
        ridable-max-y: 256.0
        attributes:
          max_health: 6.0
      mule:
        ridable-in-water: false
        breeding-delay-ticks: 6000
        attributes:
          max_health:
            min: 15.0
            max: 30.0
          jump_strength:
            min: 0.5
            max: 0.5
          movement_speed:
            min: 0.175
            max: 0.175
      pig:
        ridable: false
        ridable-in-water: false
        give-saddle-back: false
        breeding-delay-ticks: 6000
        attributes:
          max_health: 10.0
      ocelot:
        ridable: false
        ridable-in-water: false
        breeding-delay-ticks: 6000
        attributes:
          max_health: 10.0
      panda:
        ridable: false
        ridable-in-water: false
        breeding-delay-ticks: 6000
        attributes:
          max_health: 20.0
      shulker:
        ridable: false
        ridable-in-water: false
        attributes:
          max_health: 30.0
      skeleton:
        ridable: false
        ridable-in-water: false
        attributes:
          max_health: 20.0
      silverfish:
        bypass-mob-griefing: false
        ridable: false
        ridable-in-water: false
        attributes:
          max_health: 8.0
      ravager:
        griefable-blocks:
        - minecraft:oak_leaves
        - minecraft:spruce_leaves
        - minecraft:birch_leaves
        - minecraft:jungle_leaves
        - minecraft:acacia_leaves
        - minecraft:dark_oak_leaves
        - minecraft:beetroots
        - minecraft:carrots
        - minecraft:potatoes
        - minecraft:wheat
        bypass-mob-griefing: false
        ridable: false
        ridable-in-water: false
        attributes:
          max_health: 100.0
      sheep:
        bypass-mob-griefing: false
        ridable: false
        ridable-in-water: false
        breeding-delay-ticks: 6000
        attributes:
          max_health: 8.0
      squid:
        ridable: false
        immune-to-EAR: true
        water-offset-check: 0.0
        can-fly: false
        attributes:
          max_health: 10.0
      polar_bear:
        ridable: false
        ridable-in-water: false
        breedable-item: ''
        breeding-delay-ticks: 6000
        attributes:
          max_health: 30.0
      slime:
        ridable: false
        ridable-in-water: false
        attributes:
          max_health: size * size
      snow_golem:
        bypass-mob-griefing: false
        min-shoot-interval-ticks: 20
        max-shoot-interval-ticks: 20
        snow-ball-modifier: 10.0
        attack-distance: 1.25
        takes-damage-from-water: true
        ridable: false
        ridable-in-water: false
        leave-trail-when-ridden: false
        drop-pumpkin-when-sheared: false
        pumpkin-can-be-added-back: false
        attributes:
          max_health: 4.0
      rabbit:
        bypass-mob-griefing: false
        ridable: false
        ridable-in-water: false
        spawn-toast-chance: 0.0
        spawn-killer-rabbit-chance: 0.0
        breeding-delay-ticks: 6000
        attributes:
          max_health: 3.0
      pufferfish:
        ridable: false
        attributes:
          max_health: 3.0
      salmon:
        ridable: false
        attributes:
          max_health: 3.0
      turtle:
        ridable: false
        ridable-in-water: false
        breeding-delay-ticks: 6000
        attributes:
          max_health: 30.0
      strider:
        give-saddle-back: false
        takes-damage-from-water: true
        ridable: false
        ridable-in-water: false
        breeding-delay-ticks: 6000
        attributes:
          max_health: 20.0
      villager:
        allow-trading: true
        breeding-delay-ticks: 6000
        clerics-farm-warts: false
        cleric-wart-farmers-throw-warts-at-villagers: true
        ridable: false
        ridable-in-water: false
        brain-ticks: 1
        use-brain-ticks-only-when-lagging: true
        can-be-leashed: false
        bypass-mob-griefing: false
        follow-emerald-blocks: false
        can-breed: true
        spawn-iron-golem:
          radius: 0
          limit: 0
        lobotomize:
          enabled: false
          check-interval: 60
        attributes:
          max_health: 20.0
      wither:
        explosion-radius: 1.0
        can-ride-vehicles: false
        bypass-mob-griefing: false
        ridable: false
        ridable-in-water: false
        ridable-max-y: 256.0
        max-health: 5.0
        health-regen-amount: 1.0
        health-regen-delay: 20
        attributes:
          max_health: 5.0
      spider:
        ridable: false
        ridable-in-water: false
        attributes:
          max_health: 16.0
      stray:
        ridable: false
        ridable-in-water: false
        attributes:
          max_health: 20.0
      witch:
        ridable: false
        ridable-in-water: false
        attributes:
          max_health: 26.0
      vex:
        ridable: false
        ridable-in-water: false
        ridable-max-y: 256.0
        attributes:
          max_health: 14.0
      vindicator:
        ridable: false
        ridable-in-water: false
        johnny:
          spawn-chance: 0.0
        attributes:
          max_health: 24.0
      wolf:
        default-collar-color: RED
        milk-cures-rabid-wolves: true
        spawn-rabid-chance: 0.0
        ridable: false
        ridable-in-water: false
        breeding-delay-ticks: 6000
        attributes:
          max_health: 8.0
      zombie:
        bypass-mob-griefing: false
        ridable: false
        ridable-in-water: false
        aggressive-towards-villager-when-lagging: true
        break-door-minimum-difficulty: HARD
        jockey:
          only-babies: true
          chance: 0.05
          try-existing-chickens: true
        attributes:
          max_health: 20.0
          spawn_reinforcements: 0.1
      zoglin:
        ridable: false
        ridable-in-water: false
        attributes:
          max_health: 40.0
      ender_dragon:
        can-ride-vehicles: false
        bypass-mob-griefing: false
        ridable: false
        ridable-in-water: false
        ridable-max-y: 256.0
        always-drop-egg-block: false
        always-drop-full-exp: false
        max-health: 200.0
        attributes:
          max_health: 200.0
      elder_guardian:
        ridable: false
        attributes:
          max_health: 80.0
      piglin_brute:
        ridable: false
        ridable-in-water: false
        attributes:
          max_health: 50.0
      trader_llama:
        breeding-delay-ticks: 6000
        ridable: false
        ridable-in-water: false
        attributes:
          max_health:
            min: 15.0
            max: 30.0
          jump_strength:
            min: 0.5
            max: 0.5
          movement_speed:
            min: 0.175
            max: 0.175
      wandering_trader:
        allow-trading: true
        ridable: false
        ridable-in-water: false
        can-be-leashed: false
        follow-emerald-blocks: false
        attributes:
          max_health: 20.0
      wither_skeleton:
        ridable: false
        ridable-in-water: false
        takes-wither-damage: false
        attributes:
          max_health: 20.0
      zombie_horse:
        can-swim: false
        ridable-in-water: false
        spawn-chance: 0.0
        attributes:
          max_health:
            min: 15.0
            max: 15.0
          jump_strength:
            min: 0.4
            max: 1.0
          movement_speed:
            min: 0.2
            max: 0.2
      skeleton_horse:
        can-swim: false
        ridable-in-water: true
        attributes:
          max_health:
            min: 15.0
            max: 15.0
          jump_strength:
            min: 0.4
            max: 1.0
          movement_speed:
            min: 0.2
            max: 0.2
      tropical_fish:
        ridable: false
        attributes:
          max_health: 3.0
      zombie_villager:
        ridable: false
        ridable-in-water: false
        reset-reputation-when-cured: false
        jockey:
          only-babies: true
          chance: 0.05
          try-existing-chickens: true
        attributes:
          max_health: 20.0
          spawn_reinforcements: 0.1
      zombified_piglin:
        count-as-player-kill-when-angry: true
        ridable: false
        ridable-in-water: false
        jockey:
          only-babies: true
          chance: 0.05
          try-existing-chickens: true
        attributes:
          max_health: 20.0
          spawn_reinforcements: 0.0
      axolotl:
        ridable: false
        breeding-delay-ticks: 6000
        attributes:
          max_health: 14.0
      glow_squid:
        ridable: false
        can-fly: false
        attributes:
          max_health: 10.0
      goat:
        ridable: false
        ridable-in-water: false
        breeding-delay-ticks: 6000
        attributes:
          max_health: 10.0
    ridable-settings:
      babies-are-ridable: true
      untamed-tamables-are-ridable: true
      use-night-vision: false
```
